echo CLIQR_EXTERNAL_SERVICE_LOG_MSG_START
echo $FROM_SERVICE:$FROM_APP
echo CLIQR_EXTERNAL_SERVICE_LOG_MSG_END
echo CLIQR_EXTERNAL_SERVICE_RESULT_START
echo {"hostName": "samplehostname",
echo  "ipAddress": "192.168.2.101"}
echo CLIQR_EXTERNAL_SERVICE_RESULT_END
